Invalid Links Rule
instructure/tinymce-a11y-checker pull request #19
Opened 2018-07-11 18:05 UTC by Synvox

Fixes #7

2018-07-11 19:11 UTC, claydiffrient approved these changes
This looks great! Thanks again for another great PR!

2018-07-11 19:19 UTC, claydiffrient requested changes
Actually sorry @Synvox the issue wasn't super clear, but we're looking for something a little bit more robust.

This is definitely good though :)

So additionally we'd like to have it validate that the content it is linking to works.  So if navigating to the link would return an error condition to the user, we'd want it to alert about that.

2018-07-11 19:22 UTC, claydiffrient commented on src/rules/valid-links.js
> +  link: "https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H48"
Also, this link isn't linking to the proper content.

2018-07-12 14:27 UTC, claydiffrient requested changes
Overall really strong work.  There are some unanswered questions I'll work with @DanaDangerGrey to track down the answers to for you.

2018-07-12 16:17 UTC, Synvox commented on package.json
> +    "node-fetch": "^2.1.2",
Oh sweet. I'll just use that then.

2018-07-12 16:22 UTC, Synvox commented on src/rules/valid-links.js
> +      // This will always work in jest because there
That's what I was thinking. It is possible to check same origin links but much more complicated to do cross-origin. There may be a way to reference a foreign resource through an `<img>` tag or similar, and check to see if the image fails to load because of a failing status code. It's hacky, but similar to how JSONP works.

2018-07-12 16:29 UTC, claydiffrient commented on src/rules/valid-links.js
> +      // This will always work in jest because there
That's true.  If you wanna do some experimentation with that... that could be really cool.  We do something similar to that to detect broken images in canvas-lms by adding a onerror handler to images. Kinda hacky, but maybe workable to do something like that here.(https://github.com/instructure/canvas-lms/blob/master/app/coffeescripts/behaviors/broken-images.js)

2018-07-12 17:18 UTC, Synvox commented on src/rules/valid-links.js
> +      // This will always work in jest because there
Here's a thought. https://codepen.io/Synvox/pen/pZvYPb?editors=0012

It looks like IMG tags don't report their failure reason which makes it impossible to detect if it failed because of a 404, or if it failed because it tried to load a document instead of an image.

The alternative is to load the resource in a `Worker`. The worker only throws when the resource fails on the network, which is exactly what we need.

2018-07-12 19:06 UTC, claydiffrient commented on src/rules/valid-links.js
> +      // This will always work in jest because there
Looking at that... it seems like a good solution... they aren't supported in IE 11, but I think we could probably just let that be a restriction on the plugin.  If you aren't in IE then you get a little bit more validation, otherwise you get the basic stuff.

2026-01-07 20:46 UTC, closed without merging