Bring code up to date with npm 3.0.0-rc2 version
instructure/tinymce-a11y-checker pull request #88
Opened 2021-04-29 16:22 UTC by gnbaron

This change aims to reflect the changes made on the npm 3.0.0-rc1 and
3.0.0-rc2 published versions.

Note: the cypress tests are disabled and the demo app is not building
properly because RCE still not fully independent from canvas code.

2021-04-29 16:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/tinymce-a11y-checker?pullRequest=88) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/tinymce-a11y-checker?pullRequest=88) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/tinymce-a11y-checker?pullRequest=88) it.</sub>

2021-05-04 13:17 UTC, eschiebel commented on package.json
> +    "@instructure/browserslist-config-canvas-lms": ">=2",
if we're going to upgrade instui from V5, why not all the way to V7?

2021-05-04 13:17 UTC, eschiebel commented on src/components/checker.js
>            <Select
If we choose to go to instui 7, you'll want <SimpleSelect> here

2021-05-04 15:00 UTC, eschiebel requested changes
The version in package.json should get bumped.

2021-05-04 15:08 UTC, eschiebel submitted a review, later dismissed

2021-05-04 17:35 UTC, eschiebel approved these changes

2021-05-04 17:57 UTC, armstrongnate approved these changes

2021-05-04 17:58 UTC, merged