Add "decorative" option to img-alt-filename rule
instructure/tinymce-a11y-checker pull request #90
Opened 2021-05-04 17:25 UTC by gnbaron

2021-05-05 14:46 UTC, eschiebel requested changes

2021-05-05 14:46 UTC, eschiebel commented on src/rules/img-alt-filename.js
> +      elem.setAttribute("data-decorative", "true")
to be consistent with the RCE, and conventional wai-aria expectations, `role="presentation"` should be included. If it exists, then the checkbox should get checked, and the attribute should get added/removed as the checkbox is checked/unchecked. That needs to happen here and in `img-alt.js`

2021-05-05 15:11 UTC, gnbaron commented on src/rules/img-alt-filename.js
> +      elem.setAttribute("data-decorative", "true")
good catch! let me fix that

2021-05-06 17:22 UTC, eschiebel approved these changes

2021-05-06 17:23 UTC, merged